✨ add blog post
GDG-Nantes/devfest2019 pull request #22
Opened 2019-06-14 09:00 UTC by xavmarc

2019-06-14 10:07 UTC, pguyard approved these changes

2019-06-17 11:57 UTC, jlandure requested changes

2019-06-17 11:57 UTC, jlandure commented on content/blog/accorde-tes-instruments.md
> +Do not hesitate to consult our article: [the selection of the talks](https://medium.com/devfest-nantes/la-s%C3%A9lection-des-talks-842a622af11a) on our medium in order to know our way to select the D
```suggestion
Do not hesitate to read our blogpost: [the selection of the talks](https://medium.com/devfest-nantes/la-s%C3%A9lection-des-talks-842a622af11a) in order to know the way we select the talks.
```

2019-06-17 11:57 UTC, jlandure commented on content/blog/accorde-tes-instruments.md
> +As a reminder, you have until June 30 23:59 to propose a topic to #DevFestNantes!
```suggestion
As a reminder, you have until June 30 23:59 to submit a talk to #DevFestNantes!
```

2019-06-17 11:57 UTC, jlandure commented on content/blog/accorde-tes-instruments.md
> +## Inscriptions: save the date!
```suggestion
## Tickets: save the date!
```

2019-06-17 11:57 UTC, jlandure commented on content/blog/accorde-tes-instruments.md
> +As a reminder, we have opened a [lottery](https://www.billetweb.fr/devfest-Nantes-2019) which will allow you to buy a 2 day pass at the price of 99 € TTC if you are drawn (see [tweet](https://twitter
```suggestion
We have opened a [lottery](https://www.billetweb.fr/devfest-Nantes-2019) which will allow you to buy a 2-day pass at the price of 99 € TTC if you are drawn (see [tweet](https://twitter.com/devfestnantes/status/1125388292986265600)).
```

2019-06-17 11:57 UTC, jlandure commented on content/blog/accorde-tes-instruments.md
> +400 1-Day Pass will be on sale from 10 September 2019 at 10am! Do not forget to add it to your calendar 🎶 ["With or without you - U2"](https://www.youtube.com/watch?v=6DeDzsCGbsQ) 🎶
```suggestion
400 1-Day Pass will be on sale the 10th September 2019 at 10am CEST! Do not forget to add it to your calendar 🎶 ["With or without you - U2"](https://www.youtube.com/watch?v=6DeDzsCGbsQ) 🎶
```

2019-06-17 12:01 UTC, jlandure commented
@xavmarc You can also add a tweet directly in the page like [here](https://devfesttoulouse.fr/blog/find-out-when-is-edition-2019-contest/) with the `tweet` tag inside the MD templating.
```
{{< tweet 1089767584302579712 >}}
```

2019-06-17 12:40 UTC, xavmarc commented
J'ai testé en local mais j'ai l'erreur suivante, c'est pour cela que j'avais laissé le lien: 
`ERROR 2019/06/17 14:37:42 Failed to get JSON resource "https://api.twitter.com/1/statuses/oembed.json?id=1089767584302579712&dnt=false": Get https://api.twitter.com/1/statuses/oembed.json?id=1089767584302579712&dnt=false: dial tcp: lookup api.twitter.com:
no such host`

2019-06-17 12:58 UTC, jlandure approved these changes

2019-06-17 13:29 UTC, merged